### PR TITLE
bugfix: record which matches the current request error. 

### LINKED ISSUE #67: bug: record which matches the current request error
With the following two conditions met:

- opts.method matched routr.methods
- opts.matched = {}

the route match will fail.

case references: apache/apisix#1574

bug causes
https://github.com/api7/lua-resty-radixtree/blob/6b5d65eb9853c91b1d23cc4cea8941be74bb5f20/lib/resty/radixtree.lua#L663-L666
between `match_route_opts` and `compare_param` , should check whether it is resuful style url pass parameter, or prefix matching, the prefix matching does not need to be entered `compare_param`.

### PR DESCRIPTION
**Pull request by tzssangglass**
fix #67

### CODE REVIEW

**Comment by membphis** [comment]
@tzssangglass please sign the CLA .

**Comment by tzssangglass** [comment]
> @tzssangglass please sign the CLA .

I've just signed the CLA but it says it's not signed, should I close this PR and reopen another one?

**Comment by membphis** [comment]
just wait for a moment ^_^

**Comment by tzssangglass** [comment]
Try reopening a PR to update the CLA signing status

**Pull request closed without merging**
