### PR TITLE
bug: Trailing slash with argument is not respected

### PR DESCRIPTION
**Pull request by boekkooi-lengoo**
Good day.

Thanks for having a look at this PR that is trying to fix an issue where the trailing slash of a path is not respected when a argument is set before it.

Cheers,
Warnar

### CODE REVIEW

**Comment by monkeyDluffy6017** [comment]
Thanks for your contribution! we will check it later

**Review by membphis — APPROVED** [review]
High quality PR, LGTM

**Comment by membphis** [comment]
@monkeyDluffy6017 welcome to take a look at this PR, thx

**Review by shreemaan-abhishek — APPROVED** [review]
LGTM

**Pull request merged**
